#pragma once
#include "BitMap.h"

enum PIECEBITMAPTYPE
{
	PIECEBITMAPTYPE_0,
	PIECEBITMAPTYPE_1,
	PIECEBITMAPTYPE_2,
	PIECEBITMAPTYPE_3,
	PIECEBITMAPTYPE_4,
	PIECEBITMAPTYPE_5,
	PIECEBITMAPTYPE_6,
	PIECEBITMAPTYPE_7,
	PIECEBITMAPTYPE_8,
	PIECEBITMAPTYPE_MINE,
	PIECEBITMAPTYPE_CLOSE,
	PIECEBITMAPTYPE_FLAG,
	PIECEBITMAPTYPE_END
};

class PieceBitMap
{
	BitMap m_PieceBitMap[PIECEBITMAPTYPE_END];

public:
	void InitPieceBitMap(HDC& hdc);
	void DrawPieceBitMap(PIECEBITMAPTYPE pieceBitMapType, HDC& hdc, int x, int y);

	PieceBitMap();
	~PieceBitMap();
};

